### PR TITLE
Feature/v0.2.0

### PR DESCRIPTION
**Pull request by ninjabear**

### CODE REVIEW

**Comment by ninjabear** [comment]
@alexanderdean I think this is ready to merge!

**Comment by ninjabear** [comment]
I forgot the jarfile ref in `tasks.py`. Fixed

**Comment by alexanderdean** [comment]
Hey @ninjabear - have you definitely gone through the README instructions following your updates? I can see something (the un-updated `S3_KEY`) which looks like it would break the instructions...

**Comment by ninjabear** [comment]
Hi, I haven't no - I just fixed the issues and didn't look too closely, sorry! I'll make sure I go through it properly

**Comment by alexanderdean** [comment]
No worries - keep me posted!

**Comment by ninjabear** [comment]
I've run through the instructions now - the S3 key was a problem! In fixing it I've refactored it such that it's derived from the JARFILE field. I think this makes sense. I ran through the instructions again after making my changes to check that it still works (it does!).

**Comment by alexanderdean** [comment]
Ah great @ninjabear - I hoped you would do that!

**Comment by alexanderdean** [comment]
All done, thanks @ninjabear !

**Pull request merged**
